name: estimator-ros
channels:
- conda-forge
dependencies:
- python=3.12
- pip
- cmake
- ninja
- colcon-common-extensions
- pip:
    - catkin_pkg
    - empy
    - numpy
    - lark-parser
    - pyserial
    - fastapi
    - uvicorn[standard]
    - psutil
