name: estimator-ros
channels:
- conda-forge
dependencies:
- python=3.12
- pip
- cmake
- ninja
- colcon-common-extensions
- pip:
    - catkin_pkg
    - empy
    - typing-extensions
    - lark-parser
    - pydantic>=1.7.4,<3.0.0
    - idna>=2.8
    - numpy
    - pyserial
    - fastapi
    - uvicorn[standard]
    - psutil
