name: estimator-ros
channels:
- conda-forge
dependencies:
- python=3.10
- pip
- cmake
- ninja
- colcon-common-extensions
- pip:
    - catkin_pkg
    - empy>=3.1.0,<4.0.0
    - typing-extensions
    - lark-parser
    - pydantic
    - pydantic-core
    - idna>=2.8
    - numpy
    - pyserial
    - fastapi
    - uvicorn[standard]
    - psutil
    - dash
    - evdev
    - pandas
    - numpy-quaternion
